### ISSUE TITLE
Relative ranges for reports

### ISSUE THREAD

**Issue by jasonrhodes** [SparkPost/2web2ui#156]
Time to discuss how we want to do this! :)

I think the way I'd like this to work is that the relative range buttons to populate the query string with something like `range=last_hour`, and it gets calculated on every refresh. Then in the share widget, we present the option to "pin" the time ranges since when you share a chart, you are probably trying to share the exact window you're currently looking at (probably).

If we do this, I think it'd be nice to 

a) show the current fixed range you're looking at when in "relative" mode (updates on refresh), 
b) provide a refresh button that just refreshes the current data and not the whole page, 
c) provide a "pin" button next to refresh that converts the current relative range to fixed

**Comment by jasonrhodes** [comment]
Doing this ^ work also puts us one step closer to thinking about how we might do "auto-refresh" later...

**Comment by jonambas** [comment]
We already have a `relativeRange` key in `reportFilters`. I think all we have to do is pass this value to `updateLink` / `getShareLink` instead of `from` and `to` if relativeRange is not set to `custom`. And parse that back down on componentDidMount

b) I dont think we need this - cmd+r would work as intended if the url is updated correctly
c) maybe also not needed - choosing custom does this

Also if on a relative range, maybe we should also change the textfields value from dates to "{from date} - now" ?

**Comment by jasonrhodes** [comment]
Re: existing relative range, sounds good. I might want to massage the names we're using for those ranges so the make more sense if someone is looking at the share URL but otherwise :+1:

I'd still like to do (b) because it's much faster to reload the chart only than to rebuild everything from scratch every time you want to refresh the chart. Seems like it'd be easy to do.

**Comment by jasonrhodes** [comment]
I'll cut a ticket tomorrow to do this.

**Comment by jasonrhodes** [comment]
See FAD-5924

Also relates to #202
