### ISSUE TITLE
Usage report improvements

### ISSUE THREAD

**Issue by jasonrhodes** [SparkPost/2web2ui#184]
Some of these might be matchbox changes, but just recording for future improvement.

### Make the ratio account for overages
Currently the `<ProgressBar>` component takes a "completed" prop representing a percentage. We can continue to do that but handle values that are > 100 with the following formula:
```js
let primaryPercent = completed;
let secondaryPercent = 0;
if (completed > 100) {
  secondaryPercent = Math.round(((completed - 100) / completed) * 100);
  primaryPercent = 100 - secondaryPercent;
}
```
e.g. (assuming primary is orange, secondary is blue, default is gray ... three colors would be configurable)
* When `completed` is 80, the bar would be 80% orange and 20% gray
* When `completed` is 150, the bar would be 67% orange and 33% blue
* When `completed` is 500, the bar would be 20% orange and 80% blue

_Alternatively we can pass raw values to the ProgressBar component, instead of the %_

### Hide monthly hard limit until it reaches a threshold, then display as a warning
Instead of showing the monthly limit always (which can be confusing), we should display it as an exclamation icon tooltip once a user is x% of the way through that limit (75% maybe?)

### Change "Today" to "Last 24 Hours"
This window is rolling so that's more accurate, and would probably eliminate the need to show the actual time window in addition to the title

**Comment by jgzamora** [comment]
I feel like there something weird about showing last 24 hours in context of `Usage`, especially when shown next to `Daily Limit`, which I'm assuming isn't counted as last 24 hours. If `Daily Limit` is counted from 12AM, then it'd be possible to see double your daily limit in `Used`. Last 24 hours makes sense in the context of volume and is something that would belong in a dashboard along with other account status / health stats. And since Daily Limit exists, it also makes sense to display the the days usage against that number. This section feels like it's forcing both those situations together in a weird way.

**Comment by jasonrhodes** [comment]
I'm 85% sure daily limits are calculated as a rolling 24 hour period

**Comment by jgzamora** [comment]
@jasonrhodes ah, nvm if so. Tiny suggestion in that case:  once the section is titled `Last 24 Hours` like you suggested, remove "Daily" and leave just "Limit" since the context is already set.
